-- 上市公司套保监控系统 · Supabase MVP Schema
-- 用法：Supabase Dashboard -> SQL Editor -> New Query -> 粘贴执行

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  announcement_id text unique not null,
  sec_code text,
  sec_name text,
  title text not null,
  publish_time timestamptz,
  adjunct_url text,
  pdf_url text,
  source text,
  is_candidate boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.annual_reports (
  id bigint generated by default as identity primary key,
  announcement_id text unique not null,
  sec_code text,
  sec_name text,
  title text not null,
  report_year int,
  publish_time timestamptz,
  adjunct_url text,
  pdf_url text,
  source text default 'annual',
  is_revised boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.tips (
  id bigint generated by default as identity primary key,
  announcement_id text not null,
  tip_type text not null,
  tip_level text not null default 'info',
  tip_title text not null,
  tip_message text,
  created_at timestamptz default now(),
  unique (announcement_id, tip_type, tip_title)
);

create table if not exists public.hedge_events (
  id bigint generated by default as identity primary key,
  announcement_id text unique not null references public.announcements(announcement_id) on delete cascade,
  hedge_type text,
  instrument_type text[],
  underlying_asset text[],
  risk_type text[],
  approval_level text,
  authorization_period text,
  contract_value_limit numeric,
  contract_value_currency text,
  contract_value_raw_text text,
  contract_value_basis text,          -- 额度口径: 保证金最高占用额 / 业务总额 / 合约价值
  trade_venue text,                   -- 交易场所: 境内 / 境外 / 境内外
  is_revolving boolean,               -- 是否循环额度
  use_own_funds boolean,              -- 是否使用自有资金
  is_hedging_announcement boolean default true,  -- 是否为实质开展公告
  confidence numeric,
  need_review boolean default false,
  extracted_at timestamptz,           -- 真抽取时间
  pdf_storage_path text,              -- Supabase Storage 留档路径
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.extraction_evidence (
  id bigint generated by default as identity primary key,
  announcement_id text not null,
  field_name text not null,
  page_no int,
  quote_text text,
  confidence numeric,
  created_at timestamptz default now()
);

-- updated_at 自动维护
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_announcements_updated_at on public.announcements;
create trigger set_announcements_updated_at
before update on public.announcements
for each row execute function public.set_updated_at();

drop trigger if exists set_annual_reports_updated_at on public.annual_reports;
create trigger set_annual_reports_updated_at
before update on public.annual_reports
for each row execute function public.set_updated_at();

drop trigger if exists set_hedge_events_updated_at on public.hedge_events;
create trigger set_hedge_events_updated_at
before update on public.hedge_events
for each row execute function public.set_updated_at();

-- RLS：允许前端 anon key 只读，不允许前端写入
alter table public.announcements enable row level security;
alter table public.annual_reports enable row level security;
alter table public.tips enable row level security;
alter table public.hedge_events enable row level security;
alter table public.extraction_evidence enable row level security;

drop policy if exists "public read announcements" on public.announcements;
create policy "public read announcements"
on public.announcements for select
to anon, authenticated
using (true);

drop policy if exists "public read annual reports" on public.annual_reports;
create policy "public read annual reports"
on public.annual_reports for select
to anon, authenticated
using (true);

drop policy if exists "public read tips" on public.tips;
create policy "public read tips"
on public.tips for select
to anon, authenticated
using (true);

drop policy if exists "public read hedge events" on public.hedge_events;
create policy "public read hedge events"
on public.hedge_events for select
to anon, authenticated
using (true);

drop policy if exists "public read evidence" on public.extraction_evidence;
create policy "public read evidence"
on public.extraction_evidence for select
to anon, authenticated
using (true);

-- 方便前端一次性读取公告 + 事件信息
-- 注意: 线上已有 companies 表时,视图在 02_companies.sql 中被覆盖增强版替代
-- 此处保留最小可用版,供首次初始化使用
create or replace view public.v_announcements_with_events as
select
  a.id,
  a.announcement_id,
  a.sec_code,
  a.sec_name,
  a.title,
  a.publish_time,
  a.pdf_url,
  a.source,
  e.hedge_type,
  e.instrument_type,
  e.underlying_asset,
  e.risk_type,
  e.approval_level,
  e.authorization_period,
  e.contract_value_limit,
  e.contract_value_currency,
  e.contract_value_raw_text,
  e.contract_value_basis,
  e.trade_venue,
  e.is_revolving,
  e.use_own_funds,
  e.is_hedging_announcement,
  e.confidence,
  e.need_review,
  e.extracted_at,
  e.pdf_storage_path
from public.announcements a
left join public.hedge_events e on e.announcement_id = a.announcement_id;
