const jinkoReportTotals = {
  disposalIncome: 2392.96,
  fvChangePnl: -5867.84,
  comprehensivePnl: -3474.88,
  derivativeAssets: 5892.25,
  derivativeLiabilities: 5612.87,
  netFairValue: 279.38,
  unit: "万元",
  source: "年报附注第 235–236、260–261 页，仅披露公司合计",
};

globalThis.periodicActualRows = [
  {
    id: "jinko-2025fy-fx",
    period: "2025FY",
    reportType: "年报",
    company: "晶科能源",
    ticker: "688223",
    industry: "电力设备",
    entType: "民企",
    province: "江西",
    category: "外汇",
    underlying: ["美元", "欧元"],
    instrument: ["普通远期"],
    plan: {
      amount: 42,
      unit: "亿美元",
      basis: "业务总额",
      term: "股东大会审议通过后 12 个月",
      page: "公告证据",
    },
    purchaseAmount: 23025.19,
    saleAmount: 25141.68,
    flowUnit: "万元",
    marginBalance: null,
    marginUnit: "万元",
    marginAccount: null,
    derivativeAssets: null,
    derivativeLiabilities: null,
    netFairValue: -2166.24,
    balanceUnit: "万元",
    comprehensivePnl: -9875.41,
    disposalIncome: null,
    fvChangePnl: null,
    pnlUnit: "万元",
    reportTotals: jinkoReportTotals,
    accountingStatus: "未应用",
    accountingTypes: [],
    nonApplicationReason: null,
    matchStatus: "部分匹配",
    matchNote: "品种与工具一致；公告业务总额与年报交易流量、期末公允价值口径不同。",
    evidence: { verified: 7, total: 7 },
    evidenceRows: [
      { page: "43–44", label: "外汇普通远期", quote: "购入 23,025.19 万元、售出 25,141.68 万元、期末账面价值 -2,166.24 万元、综合损益 -9,875.41 万元。", status: "双回验通过" },
      { page: "235–236", label: "报告级损益拆分", quote: "处置投资收益和公允价值变动损益只披露公司合计，未按商品与外汇分摊。", status: "双回验通过" },
      { page: "259", label: "套期会计", quote: "公司开展符合条件套期业务并应用套期会计：不适用。", status: "引文通过" },
      { page: "260–261", label: "报告级期末公允价值", quote: "衍生金融资产与负债只披露公司合计，未按商品与外汇分摊。", status: "双回验通过" },
    ],
    reconciliations: [
      "2,392.96 − 5,867.84 = −3,474.88 万元",
      "5,892.25 − 5,612.87 = 279.38 万元",
    ],
  },
  {
    id: "jinko-2025fy-commodity",
    period: "2025FY",
    reportType: "年报",
    company: "晶科能源",
    ticker: "688223",
    industry: "电力设备",
    entType: "民企",
    province: "江西",
    category: "商品",
    underlying: ["商品期货"],
    instrument: ["期货"],
    plan: {
      amount: null,
      unit: "",
      basis: "公告计划待接入",
      term: "待接入对应公告事件",
      page: "公告证据待接入",
    },
    purchaseAmount: 18083.61,
    saleAmount: 21655.95,
    flowUnit: "万元",
    marginBalance: null,
    marginUnit: "万元",
    marginAccount: null,
    derivativeAssets: null,
    derivativeLiabilities: null,
    netFairValue: 2445.61,
    balanceUnit: "万元",
    comprehensivePnl: 6400.53,
    disposalIncome: null,
    fvChangePnl: null,
    pnlUnit: "万元",
    reportTotals: jinkoReportTotals,
    accountingStatus: "未应用",
    accountingTypes: [],
    nonApplicationReason: null,
    matchStatus: "仅有实际",
    matchNote: "年报明确披露商品期货实际情况；Demo 尚未接入对应公告计划。",
    evidence: { verified: 7, total: 7 },
    evidenceRows: [
      { page: "43–44", label: "商品期货", quote: "购入 18,083.61 万元、售出 21,655.95 万元、期末账面价值 2,445.61 万元、综合损益 6,400.53 万元。", status: "双回验通过" },
      { page: "235–236", label: "报告级损益拆分", quote: "处置投资收益和公允价值变动损益只披露公司合计，未按商品与外汇分摊。", status: "双回验通过" },
      { page: "259", label: "套期会计", quote: "公司开展符合条件套期业务并应用套期会计：不适用。", status: "引文通过" },
      { page: "260–261", label: "报告级期末公允价值", quote: "衍生金融资产与负债只披露公司合计，未按商品与外汇分摊。", status: "双回验通过" },
    ],
    reconciliations: [
      "2,392.96 − 5,867.84 = −3,474.88 万元",
      "5,892.25 − 5,612.87 = 279.38 万元",
    ],
  },
  {
    id: "jiangxi-copper-2025fy-commodity",
    period: "2025FY",
    reportType: "年报",
    company: "样例铜业",
    ticker: "DEMO01",
    industry: "有色金属",
    entType: "地方国企",
    province: "江西",
    category: "商品",
    underlying: ["铜", "黄金"],
    instrument: ["期货", "期权"],
    plan: { amount: 18, unit: "亿元", basis: "保证金最高占用额", term: "董事会审议通过后 12 个月", page: "演示公告" },
    purchaseAmount: 328400,
    saleAmount: 315900,
    flowUnit: "万元",
    marginBalance: 65000,
    marginUnit: "万元",
    marginAccount: "其他货币资金",
    derivativeAssets: 8620.3,
    derivativeLiabilities: 6412.5,
    netFairValue: 2207.8,
    balanceUnit: "万元",
    comprehensivePnl: 4840.7,
    disposalIncome: 3925.1,
    fvChangePnl: 915.6,
    pnlUnit: "万元",
    accountingStatus: "已应用",
    accountingTypes: ["现金流量套期"],
    nonApplicationReason: null,
    matchStatus: "口径不可比",
    matchNote: "公告披露保证金上限，定期报告披露交易流量与期末公允价值。",
    evidence: { verified: 6, total: 7 },
    evidenceRows: [
      { page: "演示 47", label: "商品衍生品", quote: "本行为页面结构演示，除晶科样本外不代表真实公司披露。", status: "演示证据" },
    ],
    reconciliations: ["3,925.10 + 915.60 = 4,840.70 万元"],
  },
  {
    id: "sample-air-2025fy-fx",
    period: "2025FY",
    reportType: "年报",
    company: "样例航空",
    ticker: "DEMO02",
    industry: "交通运输",
    entType: "央企",
    province: "北京",
    category: "外汇",
    underlying: ["美元"],
    instrument: ["远期", "掉期"],
    plan: { amount: 25, unit: "亿美元", basis: "名义本金", term: "2025 年度", page: "演示公告" },
    purchaseAmount: 118500,
    saleAmount: 104200,
    flowUnit: "万元",
    marginBalance: 4200,
    marginUnit: "万元",
    marginAccount: "其他应收款",
    derivativeAssets: 3400,
    derivativeLiabilities: 7210,
    netFairValue: -3810,
    balanceUnit: "万元",
    comprehensivePnl: -2850,
    disposalIncome: -960,
    fvChangePnl: -1890,
    pnlUnit: "万元",
    accountingStatus: "混合应用",
    accountingTypes: ["现金流量套期", "公允价值套期"],
    nonApplicationReason: null,
    matchStatus: "匹配",
    matchNote: "品种、工具及名义本金口径均可核对。",
    evidence: { verified: 7, total: 8 },
    evidenceRows: [
      { page: "演示 132", label: "套期会计", quote: "本行为混合应用状态与多方法标签的结构演示。", status: "演示证据" },
    ],
    reconciliations: ["−960.00 − 1,890.00 = −2,850.00 万元"],
  },
  {
    id: "sample-tech-2025h1-fx",
    period: "2025H1",
    reportType: "半年报",
    company: "样例科技",
    ticker: "DEMO03",
    industry: "电子",
    entType: "民企",
    province: "广东",
    category: "外汇",
    underlying: ["美元", "日元"],
    instrument: ["远期"],
    plan: { amount: 8, unit: "亿美元", basis: "业务总额", term: "股东大会审议通过后 12 个月", page: "演示公告" },
    purchaseAmount: 38600,
    saleAmount: 35200,
    flowUnit: "万元",
    marginBalance: null,
    marginUnit: "万元",
    marginAccount: null,
    derivativeAssets: 1260,
    derivativeLiabilities: 980,
    netFairValue: 280,
    balanceUnit: "万元",
    comprehensivePnl: 420,
    disposalIncome: null,
    fvChangePnl: null,
    pnlUnit: "万元",
    accountingStatus: "未明确披露",
    accountingTypes: [],
    nonApplicationReason: null,
    matchStatus: "部分匹配",
    matchNote: "实际品种与计划一致，但损益拆分未披露。",
    evidence: { verified: 4, total: 6 },
    evidenceRows: [
      { page: "演示 61", label: "半年报披露", quote: "本行演示 null 字段与未明确披露状态。", status: "待补证据" },
    ],
    reconciliations: [],
  },
  {
    id: "sample-energy-2024fy-commodity",
    period: "2024FY",
    reportType: "年报",
    company: "样例能源",
    ticker: "DEMO04",
    industry: "石油石化",
    entType: "央企",
    province: "上海",
    category: "商品",
    underlying: ["原油"],
    instrument: ["期货", "掉期"],
    plan: { amount: 12, unit: "亿元", basis: "业务总额", term: "2024 年度", page: "演示公告" },
    purchaseAmount: 282000,
    saleAmount: 276000,
    flowUnit: "万元",
    marginBalance: 28000,
    marginUnit: "万元",
    marginAccount: "其他货币资金",
    derivativeAssets: 11300,
    derivativeLiabilities: 9800,
    netFairValue: 1500,
    balanceUnit: "万元",
    comprehensivePnl: 1680,
    disposalIncome: 1510,
    fvChangePnl: 170,
    pnlUnit: "万元",
    accountingStatus: "已应用",
    accountingTypes: ["公允价值套期"],
    nonApplicationReason: null,
    matchStatus: "匹配",
    matchNote: "品种、工具与业务总额口径可核对。",
    evidence: { verified: 8, total: 8 },
    evidenceRows: [
      { page: "演示 109", label: "套期项目", quote: "本行演示公允价值套期与完全回验状态。", status: "演示证据" },
    ],
    reconciliations: ["1,510.00 + 170.00 = 1,680.00 万元"],
  },
  {
    id: "sample-manufacturing-2024fy-rates",
    period: "2024FY",
    reportType: "年报",
    company: "样例制造",
    ticker: "DEMO05",
    industry: "机械设备",
    entType: "民企",
    province: "浙江",
    category: "利率",
    underlying: ["浮动利率借款"],
    instrument: ["利率互换"],
    plan: { amount: 6, unit: "亿元", basis: "名义本金", term: "借款存续期", page: "演示公告" },
    purchaseAmount: null,
    saleAmount: null,
    flowUnit: "万元",
    marginBalance: 950,
    marginUnit: "万元",
    marginAccount: "其他应收款",
    derivativeAssets: 180,
    derivativeLiabilities: 460,
    netFairValue: -280,
    balanceUnit: "万元",
    comprehensivePnl: null,
    disposalIncome: null,
    fvChangePnl: -280,
    pnlUnit: "万元",
    accountingStatus: "需复核",
    accountingTypes: ["现金流量套期"],
    nonApplicationReason: null,
    matchStatus: "仅有实际",
    matchNote: "定期报告披露利率互换，但样例公告计划中没有对应类别。",
    evidence: { verified: 3, total: 6 },
    evidenceRows: [
      { page: "演示 188", label: "会计政策冲突", quote: "正文与附注状态冲突，用于演示“需复核”。", status: "需复核" },
    ],
    reconciliations: [],
  },
];
