globalThis.riskCaseRows = [
  {
    id: "demo-loss-2023",
    caseKey: "DEMO|60X001|2023-03-10|重大衍生品损失",
    date: "2023-03-10",
    company: "华东新材（演示）",
    code: "60X001",
    province: "上海",
    industry: "基础化工",
    riskTypes: ["重大衍生品损失"],
    instruments: ["境外商品期权", "商品期货"],
    underlyings: ["天然气", "原油"],
    amount: 2.43,
    currency: "人民币",
    unit: "亿元",
    regulatoryAction: "交易所问询并要求专项说明",
    outcome: "终止新增头寸，修订授权及止损制度",
    sourceOrg: "上海证券交易所",
    status: "已结案",
    summary: "公司披露境外商品衍生品组合出现较大亏损，监管问询聚焦交易目的、授权范围、风险限额和会计处理。",
    documents: [
      { date: "2023-03-10", type: "问询函", title: "关于衍生品交易事项的监管问询函（演示）", sourceOrg: "上海证券交易所", url: "https://example.invalid/sse/demo-loss-inquiry" },
      { date: "2023-04-02", type: "公司回复", title: "关于监管问询函的回复公告（演示）", sourceOrg: "上市公司", url: "https://example.invalid/company/demo-loss-reply" },
      { date: "2023-05-08", type: "整改报告", title: "衍生品业务专项整改进展公告（演示）", sourceOrg: "上市公司", url: "https://example.invalid/company/demo-loss-remediation" },
    ],
    evidence: [
      { field: "风险类型", page: 2, quote: "相关境外商品衍生品组合确认损失及浮动亏损合计约人民币2.43亿元。", sourceTitle: "公司回复", url: "https://example.invalid/company/demo-loss-reply", verified: true },
      { field: "涉及工具", page: 3, quote: "交易工具包括与天然气、原油价格挂钩的商品期货及期权合约。", sourceTitle: "公司回复", url: "https://example.invalid/company/demo-loss-reply", verified: true },
      { field: "整改结果", page: 4, quote: "公司已暂停新增交易并重新制定授权、限额、止损及逐日盯市制度。", sourceTitle: "整改报告", url: "https://example.invalid/company/demo-loss-remediation", verified: true },
    ],
  },
  {
    id: "demo-margin-2022",
    caseKey: "DEMO|00X002|2022-09-16|保证金与流动性风险",
    date: "2022-09-16",
    company: "沿海金属（演示）",
    code: "00X002",
    province: "浙江",
    industry: "有色金属",
    riskTypes: ["保证金与流动性风险"],
    instruments: ["商品期货"],
    underlyings: ["镍", "铜"],
    amount: 6800,
    currency: "人民币",
    unit: "万元",
    regulatoryAction: "监管关注并要求说明资金安排",
    outcome: "补充流动性预案并下调持仓限额",
    sourceOrg: "深圳证券交易所",
    status: "整改中",
    summary: "期货价格快速波动导致追加保证金压力，公司短期资金安排和授权额度受到监管关注。",
    documents: [
      { date: "2022-09-16", type: "关注函", title: "关于期货业务资金风险的关注函（演示）", sourceOrg: "深圳证券交易所", url: "https://example.invalid/szse/demo-margin-letter" },
      { date: "2022-09-28", type: "公司回复", title: "关于关注函的回复公告（演示）", sourceOrg: "上市公司", url: "https://example.invalid/company/demo-margin-reply" },
    ],
    evidence: [
      { field: "风险金额", page: 2, quote: "极端情景下预计需追加期货保证金约6,800万元。", sourceTitle: "公司回复", url: "https://example.invalid/company/demo-margin-reply", verified: true },
      { field: "处理结果", page: 5, quote: "公司已建立专项流动性储备，并将单日最大持仓限额下调。", sourceTitle: "公司回复", url: "https://example.invalid/company/demo-margin-reply", verified: true },
    ],
  },
  {
    id: "demo-unauthorized-2021",
    caseKey: "DEMO|60X003|2021-06-21|超授权开展",
    date: "2021-06-21",
    company: "北方农产（演示）",
    code: "60X003",
    province: "黑龙江",
    industry: "农林牧渔",
    riskTypes: ["超授权或未经授权开展", "审批或内控缺陷"],
    instruments: ["商品期货"],
    underlyings: ["玉米", "豆粕"],
    amount: 1.18,
    currency: "人民币",
    unit: "亿元",
    regulatoryAction: "出具警示函",
    outcome: "相关人员问责，新增分级授权复核",
    sourceOrg: "证监会某派出机构",
    status: "已结案",
    summary: "子公司部分期货头寸超过董事会授权额度，风险控制复核和报告流程未有效执行。",
    documents: [
      { date: "2021-06-21", type: "监管措施", title: "关于对公司采取出具警示函措施的决定（演示）", sourceOrg: "证监会某派出机构", url: "https://example.invalid/csrc/demo-unauthorized-warning" },
      { date: "2021-07-05", type: "整改公告", title: "关于监管措施整改情况的公告（演示）", sourceOrg: "上市公司", url: "https://example.invalid/company/demo-unauthorized-remediation" },
    ],
    evidence: [
      { field: "违规事实", page: 1, quote: "所属子公司持有的商品期货合约规模超过董事会审议通过的授权上限。", sourceTitle: "警示函", url: "https://example.invalid/csrc/demo-unauthorized-warning", verified: true },
      { field: "整改结果", page: 2, quote: "公司对相关责任人员实施问责并增加交易前分级授权复核。", sourceTitle: "整改公告", url: "https://example.invalid/company/demo-unauthorized-remediation", verified: true },
    ],
  },
  {
    id: "demo-disclosure-2024",
    caseKey: "DEMO|00X004|2024-11-04|信息披露违规",
    date: "2024-11-04",
    company: "南方智造（演示）",
    code: "00X004",
    province: "广东",
    industry: "机械设备",
    riskTypes: ["衍生品会计与信息披露违规"],
    instruments: ["外汇远期", "外汇掉期"],
    underlyings: ["美元", "欧元"],
    amount: null,
    currency: null,
    unit: null,
    regulatoryAction: "监管函并责令补充披露",
    outcome: "更正定期报告并补充套期会计说明",
    sourceOrg: "深圳证券交易所",
    status: "已结案",
    summary: "公司未充分披露外汇衍生品名义本金、损益口径及套期会计应用情况，后续发布更正公告。",
    documents: [
      { date: "2024-11-04", type: "监管函", title: "关于定期报告衍生品披露事项的监管函（演示）", sourceOrg: "深圳证券交易所", url: "https://example.invalid/szse/demo-disclosure-letter" },
      { date: "2024-11-19", type: "更正公告", title: "年度报告更正及补充公告（演示）", sourceOrg: "上市公司", url: "https://example.invalid/company/demo-disclosure-correction" },
    ],
    evidence: [
      { field: "违规事实", page: 1, quote: "公司未完整披露外汇远期及掉期交易的名义本金、损益口径和会计处理。", sourceTitle: "监管函", url: "https://example.invalid/szse/demo-disclosure-letter", verified: true },
      { field: "处理结果", page: 3, quote: "公司已更正年度报告并补充披露现金流量套期相关信息。", sourceTitle: "更正公告", url: "https://example.invalid/company/demo-disclosure-correction", verified: true },
    ],
  },
  {
    id: "demo-mismatch-2020",
    caseKey: "DEMO|60X005|2020-08-12|授权不一致",
    date: "2020-08-12",
    company: "中部能源（演示）",
    code: "60X005",
    province: "湖北",
    industry: "电力设备",
    riskTypes: ["品种/额度/期限/场所与授权不一致"],
    instruments: ["商品期货", "场外掉期"],
    underlyings: ["动力煤"],
    amount: 3.6,
    currency: "人民币",
    unit: "亿元",
    regulatoryAction: "纪律处分",
    outcome: "通报批评，重新提交股东大会授权",
    sourceOrg: "上海证券交易所",
    status: "已结案",
    summary: "实际开展的场外掉期和业务期限超出原公告授权范围，公司后续重新履行审议程序。",
    documents: [
      { date: "2020-08-12", type: "纪律处分", title: "纪律处分决定书（演示）", sourceOrg: "上海证券交易所", url: "https://example.invalid/sse/demo-mismatch-action" },
      { date: "2020-08-26", type: "整改公告", title: "关于衍生品授权整改的公告（演示）", sourceOrg: "上市公司", url: "https://example.invalid/company/demo-mismatch-remediation" },
    ],
    evidence: [
      { field: "授权差异", page: 2, quote: "实际交易包含场外掉期，且部分合约期限超过原股东大会授权有效期。", sourceTitle: "纪律处分决定书", url: "https://example.invalid/sse/demo-mismatch-action", verified: true },
      { field: "涉案金额", page: 2, quote: "相关合约名义金额合计约人民币3.60亿元。", sourceTitle: "纪律处分决定书", url: "https://example.invalid/sse/demo-mismatch-action", verified: true },
    ],
  },
  {
    id: "demo-purpose-2018",
    caseKey: "DEMO|00X006|2018-12-03|偏离套保目的",
    date: "2018-12-03",
    company: "西部资源（演示）",
    code: "00X006",
    province: "四川",
    industry: "有色金属",
    riskTypes: ["偏离套保目的/投机化"],
    instruments: ["商品期货"],
    underlyings: ["锌", "铅"],
    amount: 4200,
    currency: "人民币",
    unit: "万元",
    regulatoryAction: "行政监管措施",
    outcome: "平仓非套保头寸，限制新增交易六个月",
    sourceOrg: "证监会某派出机构",
    status: "持续披露",
    summary: "部分交易规模与现货敞口缺少对应关系，监管文件认定风险管理和套保目的控制不足。",
    documents: [
      { date: "2018-12-03", type: "监管措施", title: "关于衍生品业务内部控制的监管措施决定（演示）", sourceOrg: "证监会某派出机构", url: "https://example.invalid/csrc/demo-purpose-action" },
      { date: "2018-12-20", type: "公司公告", title: "关于衍生品业务整改安排的公告（演示）", sourceOrg: "上市公司", url: "https://example.invalid/company/demo-purpose-plan" },
    ],
    evidence: [
      { field: "风险事实", page: 2, quote: "部分期货持仓数量与同期现货采购、库存和销售敞口缺少对应关系。", sourceTitle: "监管措施决定", url: "https://example.invalid/csrc/demo-purpose-action", verified: true },
      { field: "处理结果", page: 3, quote: "公司将平仓非套保头寸，并在六个月内暂停新增同类交易。", sourceTitle: "整改安排公告", url: "https://example.invalid/company/demo-purpose-plan", verified: true },
    ],
  },
];
