-- =============================================================
-- 001_init.sql —— 套保监控数据模型 v2（公告层/抽取层/事件层三层分离）
-- =============================================================
-- 执行方式：Supabase Dashboard → SQL Editor → 粘贴 → Run。
-- 本文件是数据契约的唯一事实源；人读版见 docs/schema_snapshot.md。
-- 设计对应 PRD §5 与 2026-07-13 决策：
--   announcements(公告层) → extractions+quota_items(抽取层) → hedge_events(事件层)
-- =============================================================

-- ---------- 1. 公司维表（iFind 权威，季度手动刷新） ----------
create table if not exists public.companies (
  code text primary key,                    -- 6位证券代码
  market text,                              -- SZ / SH / BJ
  name text,                                -- 中文简称（首个）
  full_name text,
  ent_type text check (ent_type in ('央企','地方国企','民企','外资','集体','其他')),
  ent_nature_raw text,                      -- iFind 原值（中央企业/私营/中外合资…）
  actual_controller text,
  scale text,                               -- L 大型 / M 中型 / S 小型 …
  ind_l1 text, ind_l2 text, ind_l3 text,    -- 同花顺行业三级
  province text, city text,
  profile text,                             -- 公司简介（详情页用）
  source text,                              -- 来源文件名
  updated_at timestamptz default now()
);

-- ---------- 2. 公告层（巨潮元数据，主键=巨潮 announcementId） ----------
create table if not exists public.announcements (
  ann_id text primary key,
  code text,
  name text,
  title text not null,
  publish_time timestamptz,
  ann_date date,                            -- 北京时区日期（便于按日聚合）
  adjunct_url text,
  pdf_url text,
  source text,                              -- title:关键词 / fulltext-audit
  matched_keywords text[],
  status text not null default 'pending'
    check (status in ('pending','extracted','irrelevant','failed','skipped')),
  note text,                                -- 失败原因 / 无关原因
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists idx_ann_status on public.announcements (status);
create index if not exists idx_ann_date on public.announcements (ann_date desc);
create index if not exists idx_ann_code on public.announcements (code);

-- ---------- 3. 抽取层（每公告一行 LLM 结构化结果） ----------
create table if not exists public.extractions (
  ann_id text primary key references public.announcements (ann_id) on delete cascade,
  model text,
  prompt_version text,
  is_hedge_related boolean,
  ann_role text check (ann_role in
    ('计划-董事会','计划-股东大会','可行性分析','管理制度',
     '进展','平仓或终止','风险提示','其他')),
  scope text[],                             -- 商品/外汇/利率/其他，可多
  instruments text[],
  underlyings text[],
  venue text check (venue in ('境内','境外','境内外','未披露')),
  venues_detail text[],
  approval_level text check (approval_level in
    ('董事会','股东大会','董事会及股东大会','未披露')),
  plan_label text,                          -- "2026年度" 等计划年度标签
  meeting text,                             -- 审议会议届次
  period_text text,
  period_months int,
  is_revolving boolean,
  use_own_funds boolean,
  summary text,
  confidence numeric,
  evidence jsonb,                           -- [{field,quote,page}]
  raw jsonb,                                -- LLM 完整输出（审计与重放用）
  text_chars int,
  pdf_pages int,
  extracted_at timestamptz default now()
);
create index if not exists idx_ext_role on public.extractions (ann_role);

-- ---------- 4. 额度明细（口径结构化：一公告可多条额度） ----------
create table if not exists public.quota_items (
  id bigint generated by default as identity primary key,
  ann_id text not null references public.announcements (ann_id) on delete cascade,
  scope text check (scope in ('商品','外汇','利率','其他','综合')),
  basis text check (basis in
    ('保证金占用','业务总额','名义本金','合约价值','其他','未披露')),
  amount numeric,                           -- 原币"元"为单位；未披露/百分比口径为 null
  currency text,                            -- CNY/USD/EUR/HKD/JPY/其他/未披露
  raw_text text,                            -- 原文摘录（证据）
  page int,                                 -- 原文页码（证据）
  amount_verified boolean,                  -- 程序回验：amount 能否由 raw_text 复算（PRD 5.7）
  quote_verified boolean                    -- 程序回验：raw_text 是否确在正文中
);
create index if not exists idx_quota_ann on public.quota_items (ann_id);
create index if not exists idx_quota_basis on public.quota_items (basis);

-- ---------- 5. 事件层（一行 = 一次套保决策；由 build_events 全量重建） ----------
create table if not exists public.hedge_events (
  event_key text primary key,               -- code|锚定年|scope 确定性键
  code text,
  name text,
  anchor_year int,
  scope text[],
  plan_label text,
  stage text,                               -- 股东大会通过/董事会通过/仅制度可行性/进展(未见计划公告)
  approval_level text,
  first_ann_date date,
  latest_ann_date date,
  ann_count int,
  ann_roles text[],
  instruments text[],
  underlyings text[],
  venue text,
  period_text text,
  is_revolving boolean,
  use_own_funds boolean,
  quota jsonb,                              -- [{scope,basis,amount,currency,raw_text,amount_verified}]
  quota_source_ann_id text,                 -- 额度取自哪份公告（证据链）
  built_at timestamptz
);
create index if not exists idx_ev_code on public.hedge_events (code);
create index if not exists idx_ev_year on public.hedge_events (anchor_year);

create table if not exists public.event_members (
  ann_id text primary key references public.announcements (ann_id) on delete cascade,
  event_key text not null
);
create index if not exists idx_em_event on public.event_members (event_key);

-- ---------- 6. updated_at 自动维护 ----------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_ann_updated on public.announcements;
create trigger trg_ann_updated before update on public.announcements
for each row execute function public.set_updated_at();

drop trigger if exists trg_co_updated on public.companies;
create trigger trg_co_updated before update on public.companies
for each row execute function public.set_updated_at();

-- ---------- 7. RLS：前端 anon 只读，写入仅 service_role（绕过 RLS） ----------
alter table public.companies enable row level security;
alter table public.announcements enable row level security;
alter table public.extractions enable row level security;
alter table public.quota_items enable row level security;
alter table public.hedge_events enable row level security;
alter table public.event_members enable row level security;

drop policy if exists "anon read companies" on public.companies;
create policy "anon read companies" on public.companies
  for select to anon, authenticated using (true);
drop policy if exists "anon read announcements" on public.announcements;
create policy "anon read announcements" on public.announcements
  for select to anon, authenticated using (true);
drop policy if exists "anon read extractions" on public.extractions;
create policy "anon read extractions" on public.extractions
  for select to anon, authenticated using (true);
drop policy if exists "anon read quota_items" on public.quota_items;
create policy "anon read quota_items" on public.quota_items
  for select to anon, authenticated using (true);
drop policy if exists "anon read hedge_events" on public.hedge_events;
create policy "anon read hedge_events" on public.hedge_events
  for select to anon, authenticated using (true);
drop policy if exists "anon read event_members" on public.event_members;
create policy "anon read event_members" on public.event_members
  for select to anon, authenticated using (true);

-- ---------- 8. 前端视图（M3 前端的读取契约，现在定稿） ----------
drop view if exists public.v_ann_flow;
create view public.v_ann_flow as
select
  a.ann_id, a.code, a.name, a.title, a.publish_time, a.ann_date,
  a.pdf_url, a.source, a.matched_keywords, a.status, a.note,
  e.is_hedge_related, e.ann_role, e.scope, e.instruments, e.underlyings,
  e.venue, e.venues_detail, e.approval_level, e.plan_label, e.meeting,
  e.period_text, e.is_revolving, e.use_own_funds, e.summary,
  e.confidence, e.evidence, e.prompt_version, e.extracted_at,
  em.event_key,
  c.ind_l1, c.ind_l2, c.ind_l3, c.ent_type, c.province, c.market, c.scale
from public.announcements a
left join public.extractions e on e.ann_id = a.ann_id
left join public.event_members em on em.ann_id = a.ann_id
left join public.companies c on c.code = a.code;

drop view if exists public.v_events;
create view public.v_events as
select
  ev.*,
  c.ind_l1, c.ind_l2, c.ind_l3, c.ent_type, c.province, c.market, c.scale
from public.hedge_events ev
left join public.companies c on c.code = ev.code;
