-- =============================================================
-- 002_periodic_reports.sql —— M4a 定期报告 POC 数据模型
-- =============================================================
-- 三层分离：报告元数据 → 披露判断 → 原文数值事实。
-- 主事实层只接收报告原文明确披露值；估算/行情反推不得写入。

create table if not exists public.periodic_reports (
  report_id text primary key,               -- 巨潮 announcementId
  code text not null references public.companies (code),
  name text,
  title text not null,
  report_type text not null check (report_type in ('annual','semiannual')),
  report_period text not null,              -- 例如 2025FY / 2025H1
  fiscal_year int not null,
  period_end date,
  publish_date date,
  adjunct_url text,
  pdf_url text not null,
  is_revised boolean not null default false,
  source text not null default 'cninfo',
  status text not null default 'discovered' check (status in
    ('discovered','located','extracted','needs_ocr','failed','skipped')),
  candidate_pages int[],                    -- PDF 1-based 页码
  locator_terms text[],
  locator_version text,
  page_count int,
  text_chars int,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_periodic_reports_code_period
  on public.periodic_reports (code, fiscal_year desc, report_type);
create index if not exists idx_periodic_reports_status
  on public.periodic_reports (status);

create table if not exists public.periodic_derivatives (
  report_id text primary key references public.periodic_reports (report_id) on delete cascade,
  disclosure_status text not null check (disclosure_status in
    ('有数值','提及无数值','未提及','需复核')),
  scopes text[],
  instruments text[],
  underlyings text[],
  purpose text,
  hedge_accounting text[],
  summary text,
  evidence jsonb not null default '[]'::jsonb,
  confidence numeric check (confidence between 0 and 1),
  model text,
  prompt_version text,
  review_status text not null default 'pending' check (review_status in
    ('pending','accepted','rejected')),
  extracted_at timestamptz not null default now()
);

create table if not exists public.periodic_metric_items (
  id bigint generated by default as identity primary key,
  report_id text not null references public.periodic_reports (report_id) on delete cascade,
  metric_type text not null check (metric_type in (
    'period_purchase_amount','period_sale_amount','period_pnl','ending_balance',
    'net_asset_ratio','derivative_asset_fv','derivative_liability_fv',
    'margin_end_cash','margin_peak_reported','collateral_end_fair_value','credit_facility_used_end',
    'option_premium_usage_peak','notional_end_reported','notional_peak_reported',
    'contract_quantity_end','oci_amount','reclassification_amount')),
  scope text,
  underlying text,
  value numeric,
  currency text,
  unit text,
  time_basis text not null check (time_basis in ('period','period_end','period_peak')),
  source_section text,
  raw_text text not null,
  page int not null check (page > 0),
  value_verified boolean,
  quote_verified boolean,
  value_origin text not null default 'reported' check (value_origin = 'reported'),
  created_at timestamptz not null default now()
);
create index if not exists idx_periodic_metrics_report
  on public.periodic_metric_items (report_id);
create index if not exists idx_periodic_metrics_type
  on public.periodic_metric_items (metric_type);

drop trigger if exists trg_periodic_reports_updated on public.periodic_reports;
create trigger trg_periodic_reports_updated before update on public.periodic_reports
for each row execute function public.set_updated_at();

alter table public.periodic_reports enable row level security;
alter table public.periodic_derivatives enable row level security;
alter table public.periodic_metric_items enable row level security;

drop policy if exists "anon read periodic_reports" on public.periodic_reports;
create policy "anon read periodic_reports" on public.periodic_reports
  for select to anon, authenticated using (true);
drop policy if exists "anon read periodic_derivatives" on public.periodic_derivatives;
create policy "anon read periodic_derivatives" on public.periodic_derivatives
  for select to anon, authenticated using (true);
drop policy if exists "anon read periodic_metric_items" on public.periodic_metric_items;
create policy "anon read periodic_metric_items" on public.periodic_metric_items
  for select to anon, authenticated using (true);

-- 2026-05 起新项目默认不再自动暴露 public 新表，显式声明 Data API 权限。
grant select on public.periodic_reports, public.periodic_derivatives,
  public.periodic_metric_items to anon, authenticated;
grant select, insert, update, delete on public.periodic_reports,
  public.periodic_derivatives, public.periodic_metric_items to service_role;
grant usage, select on sequence public.periodic_metric_items_id_seq to service_role;
