-- =============================================================
-- 004_periodic_v15.sql —— M4 POC v1.5 数据契约
-- =============================================================
-- 向后兼容：保留旧 hedge_accounting / period_pnl 与现有数据。

alter table public.periodic_derivatives
  add column if not exists hedge_accounting_status text,
  add column if not exists hedge_accounting_types text[] not null default '{}',
  add column if not exists non_application_reason text,
  add column if not exists hedge_accounting_page int,
  add column if not exists hedge_accounting_quote text,
  add column if not exists hedge_accounting_quote_verified boolean;

update public.periodic_derivatives
set hedge_accounting_status = case
  when coalesce(array_length(hedge_accounting, 1), 0) > 0
    and hedge_accounting && array[
      '公允价值套期','现金流量套期','境外经营净投资套期'
    ]::text[] then '已应用'
  else '未明确披露'
end
where hedge_accounting_status is null;

update public.periodic_derivatives
set hedge_accounting_types = array(
  select distinct x
  from unnest(coalesce(hedge_accounting, '{}'::text[])) as x
  where x in ('公允价值套期','现金流量套期','境外经营净投资套期','其他')
)
where hedge_accounting_types = '{}'::text[];

alter table public.periodic_derivatives
  alter column hedge_accounting_status set default '未明确披露',
  alter column hedge_accounting_status set not null;

alter table public.periodic_derivatives
  drop constraint if exists periodic_derivatives_hedge_accounting_status_check;
alter table public.periodic_derivatives
  add constraint periodic_derivatives_hedge_accounting_status_check
  check (hedge_accounting_status in
    ('已应用','未应用','混合应用','未明确披露','需复核'));

alter table public.periodic_derivatives
  drop constraint if exists periodic_derivatives_hedge_accounting_page_check;
alter table public.periodic_derivatives
  add constraint periodic_derivatives_hedge_accounting_page_check
  check (hedge_accounting_page is null or hedge_accounting_page > 0);

alter table public.periodic_metric_items
  add column if not exists fact_level text,
  add column if not exists account_name text,
  add column if not exists is_restricted boolean,
  add column if not exists counterparty text;

update public.periodic_metric_items
set fact_level = case
  when scope is not null and underlying is not null then 'underlying'
  when scope is not null then 'scope'
  else 'report'
end
where fact_level is null;

alter table public.periodic_metric_items
  alter column fact_level set default 'report',
  alter column fact_level set not null;

alter table public.periodic_metric_items
  drop constraint if exists periodic_metric_items_metric_type_check;
alter table public.periodic_metric_items
  add constraint periodic_metric_items_metric_type_check check (metric_type in (
    'period_purchase_amount','period_sale_amount','period_pnl','ending_balance',
    'reported_derivative_comprehensive_pnl','derivative_disposal_investment_income',
    'derivative_fv_change_pnl','derivative_net_fv',
    'net_asset_ratio','derivative_asset_fv','derivative_liability_fv',
    'margin_end_cash','margin_peak_reported','collateral_end_fair_value',
    'credit_facility_used_end','option_premium_usage_peak','notional_end_reported',
    'notional_peak_reported','contract_quantity_end','oci_amount',
    'reclassification_amount'));

alter table public.periodic_metric_items
  drop constraint if exists periodic_metric_items_fact_level_check;
alter table public.periodic_metric_items
  add constraint periodic_metric_items_fact_level_check check (
    (fact_level = 'report' and scope is null and underlying is null)
    or (fact_level = 'scope' and scope is not null and underlying is null)
    or (fact_level = 'underlying' and scope is not null and underlying is not null)
  );

create index if not exists idx_periodic_metrics_report_level
  on public.periodic_metric_items (report_id, fact_level, metric_type);

create table if not exists public.periodic_hedge_accounting_items (
  id bigint generated by default as identity primary key,
  report_id text not null references public.periodic_reports (report_id) on delete cascade,
  scope text,
  instrument text,
  underlying_asset text,
  application_status text not null check (application_status in
    ('已应用','未应用','未明确披露','需复核')),
  accounting_type text check (accounting_type is null or accounting_type in
    ('公允价值套期','现金流量套期','境外经营净投资套期','其他')),
  non_application_reason text,
  source_section text,
  page int check (page is null or page > 0),
  quote text,
  quote_verified boolean,
  confidence numeric check (confidence between 0 and 1),
  need_review boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_periodic_hedge_accounting_report
  on public.periodic_hedge_accounting_items (report_id);

alter table public.periodic_hedge_accounting_items enable row level security;

drop policy if exists "anon read periodic_hedge_accounting_items"
  on public.periodic_hedge_accounting_items;
create policy "anon read periodic_hedge_accounting_items"
  on public.periodic_hedge_accounting_items
  for select to anon, authenticated using (true);

grant select on public.periodic_hedge_accounting_items to anon, authenticated;
grant select, insert, update, delete
  on public.periodic_hedge_accounting_items to service_role;
grant usage, select
  on sequence public.periodic_hedge_accounting_items_id_seq to service_role;
