-- =============================================================
-- 005_derivative_risk_cases.sql —— M6a 衍生品风险案例库
-- =============================================================
-- 独立于公告事件与年报事实表：
-- 官方来源文档 → 风险案例 → 文档关系 → 可核验原文证据。

create table if not exists public.risk_source_documents (
  source_doc_id text primary key,
  source_org text not null check (source_org in (
    'SSE','SZSE','CSRC','CSRC_BUREAU','CNINFO','OTHER_OFFICIAL')),
  source_type text not null check (source_type in (
    'inquiry','regulatory_measure','disciplinary_action',
    'administrative_penalty','company_announcement','response',
    'rectification','other_official')),
  official_doc_id text not null,
  code text references public.companies (code) on delete set null,
  company_name text,
  title text not null,
  publish_date date,
  document_url text not null check (document_url ~ '^https://'),
  document_format text not null default 'html'
    check (document_format in ('pdf','html','other')),
  content_sha256 text,
  local_path text,
  text_chars int check (text_chars is null or text_chars >= 0),
  matched_derivative_terms text[] not null default '{}',
  matched_risk_terms text[] not null default '{}',
  raw_metadata jsonb not null default '{}'::jsonb,
  status text not null default 'discovered' check (status in (
    'discovered','candidate','relevant','irrelevant','extracted','failed')),
  note text,
  fetched_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_org, official_doc_id)
);

create index if not exists idx_risk_source_docs_publish
  on public.risk_source_documents (publish_date desc);
create index if not exists idx_risk_source_docs_code
  on public.risk_source_documents (code, publish_date desc);
create index if not exists idx_risk_source_docs_status
  on public.risk_source_documents (status, source_org, publish_date desc);

create table if not exists public.derivative_risk_cases (
  case_key text primary key,
  code text not null references public.companies (code),
  company_name text,
  event_date date,
  first_disclosure_date date,
  risk_type text not null check (risk_type in (
    '超授权或未经授权开展',
    '偏离套保目的/投机化',
    '重大衍生品损失',
    '保证金与流动性风险',
    '审批或内控缺陷',
    '衍生品会计与信息披露违规',
    '品种/额度/期限/场所与授权不一致',
    '监管整改/处罚/追责')),
  instruments text[] not null default '{}',
  underlyings text[] not null default '{}',
  summary text not null,
  amount numeric,
  currency text,
  unit text,
  regulatory_action text,
  outcome text,
  case_status text not null default '待复核' check (case_status in (
    '待复核','进行中','已整改','已结案')),
  confidence numeric check (confidence between 0 and 1),
  need_review boolean not null default true,
  model text,
  prompt_version text,
  extracted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_risk_cases_code_date
  on public.derivative_risk_cases (code, event_date desc);
create index if not exists idx_risk_cases_type_date
  on public.derivative_risk_cases (risk_type, event_date desc);
create index if not exists idx_risk_cases_review
  on public.derivative_risk_cases (need_review, confidence);

create table if not exists public.risk_case_documents (
  case_key text not null references public.derivative_risk_cases (case_key)
    on delete cascade,
  source_doc_id text not null references public.risk_source_documents (source_doc_id)
    on delete cascade,
  relation_type text not null check (relation_type in (
    'inquiry','response','measure','penalty','rectification','supporting')),
  created_at timestamptz not null default now(),
  primary key (case_key, source_doc_id)
);

create index if not exists idx_risk_case_docs_source
  on public.risk_case_documents (source_doc_id);

create table if not exists public.risk_case_evidence (
  id bigint generated by default as identity primary key,
  case_key text not null references public.derivative_risk_cases (case_key)
    on delete cascade,
  source_doc_id text not null references public.risk_source_documents (source_doc_id)
    on delete cascade,
  field text not null,
  page int check (page is null or page > 0),
  paragraph text,
  quote text not null,
  extracted_value text,
  source_url text not null check (source_url ~ '^https://'),
  quote_verified boolean not null default false,
  value_verified boolean not null default false,
  confidence numeric check (confidence between 0 and 1),
  created_at timestamptz not null default now()
);

create index if not exists idx_risk_evidence_case
  on public.risk_case_evidence (case_key);
create index if not exists idx_risk_evidence_source
  on public.risk_case_evidence (source_doc_id);

drop trigger if exists trg_risk_source_documents_updated
  on public.risk_source_documents;
create trigger trg_risk_source_documents_updated
before update on public.risk_source_documents
for each row execute function public.set_updated_at();

drop trigger if exists trg_derivative_risk_cases_updated
  on public.derivative_risk_cases;
create trigger trg_derivative_risk_cases_updated
before update on public.derivative_risk_cases
for each row execute function public.set_updated_at();

alter table public.risk_source_documents enable row level security;
alter table public.derivative_risk_cases enable row level security;
alter table public.risk_case_documents enable row level security;
alter table public.risk_case_evidence enable row level security;

drop policy if exists "anon read risk_source_documents"
  on public.risk_source_documents;
create policy "anon read risk_source_documents"
  on public.risk_source_documents
  for select to anon, authenticated using (true);

drop policy if exists "anon read derivative_risk_cases"
  on public.derivative_risk_cases;
create policy "anon read derivative_risk_cases"
  on public.derivative_risk_cases
  for select to anon, authenticated using (true);

drop policy if exists "anon read risk_case_documents"
  on public.risk_case_documents;
create policy "anon read risk_case_documents"
  on public.risk_case_documents
  for select to anon, authenticated using (true);

drop policy if exists "anon read risk_case_evidence"
  on public.risk_case_evidence;
create policy "anon read risk_case_evidence"
  on public.risk_case_evidence
  for select to anon, authenticated using (true);

grant select on public.risk_source_documents, public.derivative_risk_cases,
  public.risk_case_documents, public.risk_case_evidence
  to anon, authenticated;
grant select, insert, update, delete
  on public.risk_source_documents, public.derivative_risk_cases,
  public.risk_case_documents, public.risk_case_evidence
  to service_role;
grant usage, select on sequence public.risk_case_evidence_id_seq
  to service_role;
